version: '3.8'
services:
  whatsapp:
    deploy:
      resources:
        limits:
          cpus: '.3'
          memory: 400M
        reservations:
          cpus: '.1'
          memory: 50M
    container_name: whatsapp_web_api
    image: chrishubert/whatsapp-web-api:latest
    ports:
      - "3000:3000"
    environment:
      # - API_KEY=your_global_api_key_here  # OPTIONAL
      - BASE_WEBHOOK_URL=http://localhost:3000/localCallbackExample
      - ENABLE_LOCAL_CALLBACK_EXAMPLE=TRUE
      - MAX_ATTACHMENT_SIZE=5000000
      - SET_MESSAGES_AS_SEEN=TRUE
      - DISABLED_CALLBACKS=message_ack
      - ENABLE_SWAGGER_ENDPOINT=TRUE
    networks:
      - whatsapp-net
    volumes:
      - ./sessions:/usr/src/app/sessions

  discord_bot:
    deploy:
      resources:
        limits:
          cpus: '.05'
          memory: 50M
        reservations:
          cpus: '.1'
          memory: 10M
    image: aleixolucas/disc_wpp_bot
    container_name: discord_bot
    environment:
      - DISC_TOKEN=
      - CHAT_ID=
    networks:
      - whatsapp-net
    depends_on:
        - whatsapp
networks:
  whatsapp-net:
    external: true
